### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by breadadams** [nchutchind/vue-outside-events#7]
After installing the library and starting the bundler (Parcel in this case) I get the following error:

```
/Users/breadadams/dev/coolproject/node_modules/vue-outside-events/dist/vue-outside-events.min.js:
Couldn't find preset "es2015" relative to directory "/Users/breadadams/dev/coolproject/node_modules/vue-outside-events"
```

Running `yarn add `babel-preset-es2015 --dev` fixes this and allows me to use this (*awesome* lib.), however I don't really need this preset in the project (I'm using the now preffered `babel-preset-env` - http://babeljs.io/env).

Maybe you could switch over to use the env preset? Or include `babel-preset-es2015` in the projects dev dependencies.

**Comment by nchutchind** [comment]
Sorry for the delay. I wasn't aware of any activity over here.

I went ahead and upgraded most of the libraries I was using for this build and changed the babel preset to use "env" without modules while I was at it (a requirement for rollup). Hopefully this will work better for you.

**Comment by breadadams** [comment]
I'm no longer _on_ the project using your library @nchutchind, but much appreciated you resolving this 🙂
